notes: add DeleteNoteView.
better-notes/better-notes-web-api pull request #4
Opened 2020-04-27 17:48 UTC by Anon731

2020-04-27 17:53 UTC, DaniilDaedalus requested changes

2020-04-27 17:53 UTC, WinterCitizen commented on web_api/notes/repositories.py
> +        return entities
Учитывая насколько часто мы работаем с списками `value` и `entity`, предлагаю ввести типы `EntityList` и `ValueList`. В `EntityList` можно будет пихнуть, например, метод `get_ids() -> List[int]`

2020-11-25 09:39 UTC, Anon731 commented on web_api/notes/repositories.py
> +        return entities
Давай сделаем на это таск, я хочу сейчас продолжить с тем что есть, и сделать простейший image viewer на тупых html формах, чтобы начать пользоваться нашей штукой.

2020-11-25 09:43 UTC, Anon731 commented on web_api/notes/repositories.py
> +        return entities
Создал таск https://github.com/better-notes/better-notes-web-api/issues/6

2020-11-25 09:46 UTC, WinterCitizen approved these changes

2020-11-25 09:46 UTC, merged